name: PHP Composer

on:
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Install all dependencies
      run: npm install

    - name: Build
      run: npm run build # The build command of your project
      
    - name: Build
      run: git add public/build/* -f 
      
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        remote_path: /home/shasomanpower/www
        remote_host: 148.72.246.115
        remote_user: shasomanpower
        remote_key: ${{ secrets.SECRET }}
